# Generated by Django 2.1.2 on 2018-11-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='_admin',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='_staff',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='_tattooer',
            new_name='tattooer',
        ),
    ]
